language: ruby
rvm: 2.4.1

services:
  - postgresql


script:
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    - bundle exec rake test:controllers

before_script:
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database travis_ci_test' -U postgres
